### ISSUE TITLE
Certain queries cause the broker to die

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/context.Orion-LD#20]
by condition over object

https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextConsumption/query_entities_test.js#L98

by condition over observedAt

https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextConsumption/query_entities_test.js#L108

over property of a property

https://github.com/Fiware/NGSI-LD_Tests/blob/master/contextConsumption/query_entities_test.js#L118

etc.

**Comment by kzangeli** [comment]
Think this is fixed. Test again?

**Comment by jmcanterafonseca** [comment]
certain queries still fail 4 tests failing but Orion-LD does not crash so fixed
